// Mocks generated by Mockito 5.3.0 from annotations
// in rarovideowall/test/mocks/api_service_test/api_service_test.generate.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:rarovideowall/src/shared/interfaces/api_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService<T> extends _i1.Mock implements _i2.ApiService<T> {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void clearHeaderToken() =>
      super.noSuchMethod(Invocation.method(#clearHeaderToken, []),
          returnValueForMissingStub: null);
  @override
  void setHeaderToken(String? token) =>
      super.noSuchMethod(Invocation.method(#setHeaderToken, [token]),
          returnValueForMissingStub: null);
  @override
  _i3.Future<T> request(String? url, String? mode,
          {Map<String, dynamic>? body,
          Map<String, dynamic>? queryParams,
          Map<String, dynamic>? headers}) =>
      (super.noSuchMethod(
          Invocation.method(#request, [url, mode],
              {#body: body, #queryParams: queryParams, #headers: headers}),
          returnValue: _i3.Future<T>.value(null)) as _i3.Future<T>);
}
